### ISSUE TITLE
Uncaught TypeError: e.setState is not a function

### ISSUE THREAD

**Issue by paulocesarpcfj** [ReactTraining/react-router#5360]
Hi! After upgrade react-router to 3.0.5, my build version starts to throw an error:

```Uncaught TypeError: e.setState is not a function```

The curious is because this error only appears on the build code, not on the development code. The relevant content from my prod file is below:

```
import webpack from 'webpack';
import CleanWebpackPlugin from 'clean-webpack-plugin';
import CopyWebpackPlugin from 'copy-webpack-plugin';
import baseConfig from './base';
import path from 'path';

const config = {
    ...baseConfig,

    resolve: {
        alias: {
            ...baseConfig.resolve.alias,
            react: 'preact-compat',
            'react-dom': 'preact-compat',
        },
        ...baseConfig.extensions,
    },

    plugins: [
        ...baseConfig.plugins,
        new CleanWebpackPlugin(['AuthenticationServer/wwwroot/**/*'], {
            root: path.join(__dirname, '../../api/src'),
            verbose: true,
            dry: false,
        }),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('production'),
            },
        }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compressor: {
                screw_ie8: true,
                warnings: false,
            },
            output: {
                comments: false,
            },
        }),
        new CopyWebpackPlugin([
            { from: './images', to: 'images' },
            { from: './fonts', to: 'fonts' },
            { from: './env.production.js', to: '' },
        ]),
        new webpack.optimize.DedupePlugin(),
    ],
};

export default config;
```

**Comment by mjackson** [comment]
I'm sorry, there's not enough information here for us to help you.
