### ISSUE TITLE
Missing ./selectors.js in react-router-redux

### ISSUE THREAD

**Issue by wladimiiir** [ReactTraining/react-router#5640]
## Version
5.0.0-alpha.7

## Test Case
Running mocha unit tests.

## Expected Behavior
Tests run.

## Actual Behavior
Tests fail on error: **Error: Cannot find module './selectors'** (react-router-redux/index.js:6:18)
Works in 5.0.0-alpha.6.
Attaching screenshot of react-router-redux module directory, which is clearly missing the ./selectors.js file.
![image](https://user-images.githubusercontent.com/3164600/31759024-3a741a70-b4b0-11e7-9093-f511bc859bae.png)

**Comment by adomrockie** [comment]
same issue "react-router": "^3.0.0"

**Comment by ztane** [comment]
@adomrockie wouldn't that allow upgrades?

**Comment by wladimiiir** [comment]
@adomrockie 
Use "react-router-redux": "5.0.0-alpha.6" in your package.json. Having ^ says you are targeting any compatible with.
