### ISSUE TITLE
createHistory not found

### ISSUE THREAD

**Issue by SarahJNash** [ReactTraining/react-router#4367]
Hello,

I have the following code:

```
import { createHistory, useBasename } from "history";
const browserHistory = useBasename(createHistory)({
    basename: "/foo"
});
```
This was working correctly with react-router version 3.0.0 and history version  3.2.1 

I have just updated everything to the latest react-router version 3.0.2 and history to 4.5.1 and now I get an error saying that createHistory can not be found. I found some posts that said I shouldn't be using createHistory directly so changed the code to:

```
import { Router, useRouterHistory} from "react-router";
import { createBrowserHistory } from "history"
const thisbrowserHistory = useRouterHistory(createBrowserHistory)({ basename: "/foo"});
```
and now get an error saying "Uncaught TypeError: createHistory is not a function".

Thanks

**Comment by pshrmn** [comment]
You should revert your history to v3. `history` v4 is intended for use with React Router v4.

**Comment by julianvmodesto** [comment]
@pshrmn hey there, this broke for me as well when upgrading from 3.0.0 to 3.0.2, but I'm using `import browserHistory from 'react-router/lib/browserHistory';` for my client.

**Comment by pshrmn** [comment]
@julianvmodesto Are you saying that `history` v4 was automatically installed when you updated React Router from `3.0.0` to `3.0.2`? In the RRv3 `package.json`, the `history` dependency is set for `^3.0.0` which will not install a `4.x.x` version of `history`.

**Comment by julianvmodesto** [comment]
Oops, sorry – similar issue, but different. I don't have `history` installed, I actually was importing
`react-router/lib/browserHistory`.

I fixed by importing the named modules, so 3.0.2 is good

```
 -import browserHistory from 'react-router/lib/browserHistory';
 -import Router from 'react-router/lib/Router';

 +import { Router, browserHistory } from 'react-router';
```

**Comment by SarahJNash** [comment]
It automatically installed "version": "3.2.1" (looking in the package.json of history) 
running `npm install history@3.0.0` put version 3 of history in but the code still didn't work.

**Comment by SarahJNash** [comment]
I have got to the bottom of the issue. 

I am using TypeScript and the latest @types/react-router version gets a @types/history which is incompatible.

**Comment by Jeremboo** [comment]
Hi,

I have the same issue as @SarahJNash : `Uncaught TypeError: createHistory is not a function` after reinstalling `react-router` and her dependencies. And I do not use TypeScript.

```
└─┬ react-router@3.0.2
  ├── history@3.2.1
  └── warning@3.0.0
```

I take this issue to ask how to handle the `basename` correctly with the latest version of react-router. I did not find any example in the official documentation and many old propositions are misleading now.
