### ISSUE TITLE
react-router-redux does not work in node v6.9.1

### ISSUE THREAD

**Issue by michaelBenin** [ReactTraining/react-router#4890]
## Version
react-router-redux 5.0.0-alpha.2

## Test Case
js bin not relevant, this is on the server, the wip is here https://github.com/michaelBenin/react-ssr-spa/tree/next (still a wip obv) using node.js v6.9.1

## Steps to reproduce
require the module

## Expected Behavior
does not crash application

## Actual Behavior
crashes application with output:

```
Error: Cannot find module './actions'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mbenin/Projects/react-ssr-spa/node_modules/react-router-redux/index.js:21:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mbenin/Projects/react-ssr-spa/dist/redux/store/redux/store/store.js:5:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by timdorr** [comment]
This was fixed in alpha 3 (we're now on alpha 4).
